### ISSUE TITLE
Doesn't work with PDF uploaded with FileStore

### ISSUE THREAD

**Issue by tremblaysimon** [ckan/ckanext-pdfview#21]
It seems that plugin doesn't work with pdf file uploaded directly in the ckan instance, but no problem with linked pdf. 

The output error is " PDF.js v1.0.1207 (identifiant de compilation : 72cfa36)
Message : Invalid PDF structure"

**Comment by jqnatividad** [comment]
Can you share a link to the PDF?  Is the CKAN instance publicly available?

**Comment by tremblaysimon** [comment]
Not yet unfortunately. We are running ckan 2.3 and installed pdfview from PyPI. More logging from my web browser: 

```
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

Error: Invalid XRef stream header

at error (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:252:15)
    at Object.XRef_readXRef [as readXRef] (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:4235:13)
    at Object.XRef_parse [as parse] (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:3831:28)
    at Object.PDFDocument_setup [as setup] (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:3027:17)
    at Object.PDFDocument_parse [as parse] (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:2914:12)
    at http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:2478:26
    at LocalPdfManager_ensure [as ensure] (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:2473:12)
    at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:2405:19)
    at http://example.com/data/fanstatic/ckanext-pdfview/:version:2015-11-13T09:30:24.66/vendor/pdfjs/build/pdf.worker.js:33746:22
```

**Comment by jqnatividad** [comment]
Have you tried it with a Development Installation after pip uninstalling ckanext-pdfview?

**Comment by tremblaysimon** [comment]
Just tried a development installation and I've got same problem with same error (but it's always working when the PDF isn't hosted on the server). 

I was thinking about something related with file permission but at first glance what I saw permissions file are correct (web server can read it).

**Comment by tremblaysimon** [comment]
Oh my bad, code 18... the ckan.site_url wasn't properly set. Now it's working as expected. Sorry for that!
