### ISSUE TITLE
PDF_View returns Internal server error

### ISSUE THREAD

**Issue by turbatuandrei** [ckan/ckanext-pdfview#39]
After adding the plugin and default_views, whenever I try to save a view I get and internal server error in front end.

and:

2021-02-12 17:02:50,457 ERROR [ckan.config.middleware.flask_app] Could not build url for endpoint 'package.resource_view' with values ['id', 'resource_id', 'view_id']. Did you mean 'dataset_resource.view' instead?

**Comment by taylordowns2000** [comment]
Same here. New to CKAN so I'm assuming I'm doing something wrong. Does anyone have installation tips that go beyond https://github.com/ckan/ckanext-pdfview#installation ?

Out of curiosity, @turbatuandrei , did you install ckan from source or package? (I'm on `2.9.2` from package)

**Comment by turbatuandrei** [comment]
@taylordowns2000 I installed it from source.

**Comment by amercader** [comment]
I can't reproduce this, are you able to provide a full stacktrace for the error?

**Comment by linforestzhang** [comment]
Same here for CKAN 2.10

**Comment by linforestzhang** [comment]
Error Log:

2024-01-04 11:35:09,068 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-01-04 11:35:09,068 INFO  [ckan.config.environment] Loading static files from public
2024-01-04 11:35:11,292 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 121, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 131, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 140, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 57, in __init__
    self.app = make_app(raw_config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 222, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 238, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 346, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: pdf_view
